# Generated by Django 4.2 on 2024-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
